Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provider "virtualbox" do |v|
  	v.memory = 1024
  end
  
  config.vm.define :dev do |dev|
  	dev.vm.network "private_network", ip: "10.10.1.100"
  	dev.vm.provision :shell, path: "bootstrap.sh"
  	dev.vm.provision :shell,
  		inline: 'PYTHONUNBUFFERED=1 ansible-playbook /vagrant/ansible/dev.yml -c local'
  end
  
  if Vagrant.has_plugin?("vagrant-cachier")
  	config.cache.scope = :box
  end
end
