- name: Memcached config directories are created
  file:
    path: "{{ item }}"
    state: directory
  with_items: "{{ directories }}"
  tags: [memcached]

- name: Memcached Config are copied
  copy:
    src:  "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items: "{{ files }}"
  tags: [memcached]