- name: Install unzip
  apt: name=unzip state=present
  tags: [consul]

- name: Directories are created
  file:
    path: "{{ item }}"
    state: directory
  with_items: "{{ directories }}"
  tags: [consul]

- name: Consul config files are copied
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items: "{{ files }}"
  tags: [consul]

- name: Install python consul api
  pip: name=python-consul state=forcereinstall
  tags: [consul]

- name: Install nagios-plugins
  apt: name=nagios-plugins state=present  

- name: Download consul zip
  shell: "cd /tmp;rm -f /tmp/consul*;wget https://releases.hashicorp.com/consul/1.0.0/consul_1.0.0_linux_amd64.zip;"
  tags: [consul]

- name: unzip consul and copy
  unarchive: src=/tmp/consul_1.0.0_linux_amd64.zip dest=/usr/local/bin copy=no

- name: Start consul instance
  shell: "nohup consul agent -server -bootstrap-expect 3 -ui \
    -data-dir /data/consul/data \
    -config-dir /data/consul/config \
    -node={{ ansible_hostname }} \
    -bind={{ip}} \
    -client=0.0.0.0 \
    -enable-script-checks=true \
    >{{ logs_dir }}/consul.log 2>&1 &"
  tags: [consul]